# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_add_ingr.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(985, 636)
        Dialog.setStyleSheet("QDialog{\n"
"border:2px solid gray;\n"
"}\n"
"*{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(191, 198, 155, 255), stop:1 rgba(186, 201, 153, 255));\n"
"}\n"
"QTabWidget::pane {\n"
" border: 0;\n"
" }\n"
"\n"
"QPushButton{\n"
"background-color:white;\n"
"color:black;\n"
"height:30px;\n"
"}\n"
"QTableWidget{\n"
"background-color:#071e26;\n"
"}\n"
"QTextBrowser{\n"
"background-color:#071e26;\n"
"}\n"
"Qlabel{\n"
"}\n"
"QScrollBar:vertical {\n"
"            border: 1px solid rgb(200, 208, 171);\n"
"            border-radius: 5px;\n"
"            background-color:#C8D0AB;\n"
"            width:18px;    \n"
"            margin: 0px px 3px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"            min-height: 0px;\n"
"            border-top: 2px solid black;\n"
"        border-bottom: 2px solid black;\n"
"            border-radius: 4px;\n"
"            background-color: rgb(186, 201, 153);\n"
"            margin-top:-1px;\n"
"        }\n"
"QScrollBar::handle:vertical:hover {         \n"
"           background-color: #E1E5C3;\n"
"        }\n"
"QScrollBar::handle:vertical:pressed {         \n"
"           background-color:#FBFFD8;\n"
"        }\n"
"\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.centralwidget = QtWidgets.QFrame(Dialog)
        self.centralwidget.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"}\n"
"#centralwidget{\n"
"    background-color: black;\n"
"}\n"
"#side_menu{\n"
"    background-color: black;\n"
"}\n"
"#main_body{\n"
"    background-color: black;\n"
"}\n"
"QPushButton{\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"QTableWidget{\n"
"background-color:black;\n"
"}\n"
"\n"
"MainWindow{\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centralwidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 31))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 33))
        self.header_frame.setStyleSheet("background-color: rgb(9, 5, 13);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.header_frame)
        self.frame_11.setMinimumSize(QtCore.QSize(95, 29))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.close_window_button = QtWidgets.QPushButton(self.frame_11)
        self.close_window_button.setMinimumSize(QtCore.QSize(49, 0))
        self.close_window_button.setMaximumSize(QtCore.QSize(16777215, 33))
        self.close_window_button.setStyleSheet("#close_window_button:hover {\n"
"   background: red;\n"
"   border: 2px solid #d0d0d0;\n"
"    border-radius: 4px\n"
"}")
        self.close_window_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons_images/bar_x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_button.setIcon(icon)
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_8.addWidget(self.close_window_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_7.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.header_frame)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("*{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(191, 198, 155, 255), stop:1 rgba(186, 201, 153, 255));\n"
"}\n"
"QTabWidget::pane {\n"
" border: 0;\n"
" }\n"
"\n"
"QPushButton{\n"
"background-color:white;\n"
"color:black;\n"
"height:30px;\n"
"}\n"
"QTableWidget{\n"
"background-color:#071e26;\n"
"}\n"
"QTextBrowser{\n"
"background-color:#071e26;\n"
"}\n"
"Qlabel{\n"
"}\n"
"QScrollBar:vertical {\n"
"            border: 1px solid rgb(200, 208, 171);\n"
"            border-radius: 5px;\n"
"            background-color:#C8D0AB;\n"
"            width:18px;    \n"
"            margin: 0px px 3px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"            min-height: 0px;\n"
"            border-top: 2px solid black;\n"
"        border-bottom: 2px solid black;\n"
"            border-radius: 4px;\n"
"            background-color: rgb(186, 201, 153);\n"
"            margin-top:-1px;\n"
"        }\n"
"QScrollBar::handle:vertical:hover {         \n"
"           background-color: #E1E5C3;\n"
"        }\n"
"QScrollBar::handle:vertical:pressed {         \n"
"           background-color:#FBFFD8;\n"
"        }\n"
"\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(20, 10, 20, 20)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_4.setStyleSheet("background-color:transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.frame_39 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_39.sizePolicy().hasHeightForWidth())
        self.frame_39.setSizePolicy(sizePolicy)
        self.frame_39.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("a_FuturaRoundTitulSh")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame_39.setFont(font)
        self.frame_39.setStyleSheet("*{\n"
"background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;\n"
"}\n"
"QLineEdit{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"QLineEdit:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"\n"
"\n"
"#label_8{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}\n"
"#label_9{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_14.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.frame_39)
        self.label_4.setMinimumSize(QtCore.QSize(0, 35))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_14.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.frame_39)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.frame_3 = QtWidgets.QFrame(self.frame_39)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setEnabled(True)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("/*стиль комбобокса*/\n"
"QComboBox{\n"
"border:1px solid transparent;\n"
"border-radius: 8px;\n"
"padding-left:10px;\n"
"background-color: #E1E5C3;\n"
"spacing:15px;\n"
"}\n"
"/*стиль комбобокса при наводке*/\n"
"QComboBox:hover{\n"
"background-color:#FBFFD8;\n"
"}\n"
"\n"
"/*кнопка стрелки*/\n"
"QComboBox::drop-down{\n"
"border-radius: 0px;\n"
"border:0px;\n"
"}\n"
"/*стиль стрелочки*/\n"
"QComboBox::down-arrow{\n"
"image: url(:/icons/icons_images/arrow-down.svg);\n"
"width:18px;\n"
"height:18px;\n"
"margin-right:16px;\n"
"}\n"
"\n"
"\n"
"\n"
"/*стиль выпадающий список*/\n"
"QListView{\n"
"border-radius: 0px;\n"
"background-color:transparent;\n"
"qproperty-fucusPolicy: \'NoFocus\';\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"border-radius: 8px;\n"
"  selection-background-color: #FBFFD8;\n"
"outline: 0px;\n"
"}\n"
"\n"
"QComboBox:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_14.addWidget(self.frame_3)
        self.label_8 = QtWidgets.QLabel(self.frame_39)
        self.label_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.label_6 = QtWidgets.QLabel(self.frame_39)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_39)
        self.lineEdit_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_14.addWidget(self.lineEdit_3)
        self.label_9 = QtWidgets.QLabel(self.frame_39)
        self.label_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.frame_2 = QtWidgets.QFrame(self.frame_39)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("*{\n"
"background-color:transparent;\n"
"border: 3px solid transparent;\n"
"}\n"
"QPushButton {\n"
"border-radius:8px;\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setMinimumSize(QtCore.QSize(40, 35))
        self.pushButton_11.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton:enabled{\n"
"background-color:rgb(114, 255, 123);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(46, 239, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(122, 255, 101);\n"
"}\n"
"")
        self.pushButton_11.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons_images/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 35))
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton:enabled{\n"
"background-color:rgb(255, 73, 73);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(255, 73, 73);\n"
"}\n"
"")
        self.pushButton_10.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons_images/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon2)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.verticalLayout_14.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_39)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.gridLayout.addWidget(self.frame_4, 0, 1, 2, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_24 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("a_FuturaRoundTitulSh")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame_24.setFont(font)
        self.frame_24.setStyleSheet("background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;\n"
"")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_10.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("QTableWidget:disabled{\n"
"color:black;\n"
"}\n"
"QTableWidget::item:selected:disabled{\n"
"color:black;\n"
"}\n"
"/* Яейки*/\n"
"* {\n"
"    gridline-color: #071e26 ;\n"
"    font-size: 10pt;\n"
"    spacing:15px;\n"
"}\n"
"\n"
"\n"
"/* Черная линия сбоку*/\n"
"QHeaderView{\n"
"background-color: rgb(200, 208, 171);\n"
"}\n"
"\n"
"/*заголовки*/\n"
"QHeaderView::section {\n"
"    background-color: black;\n"
"    border: 1px solid transparent;\n"
"    border-radius:2px;\n"
"    font-size:16px;\n"
"    padding-bottom:9px;\n"
"    padding-right:10px;\n"
"}\n"
"/* Горизонтальные заголовки*/\n"
"QHeaderView::section:horizontal{\n"
"background-color: transparent;\n"
"color:black; \n"
"border-radius:0px;\n"
"border-bottom:2px solid #BCC6A1;\n"
"margin-bottom:5px;\n"
"font-style: italic;\n"
"padding-top:6px;\n"
"\n"
"\n"
"}\n"
"\n"
"/* Вертикальные заголовки*/\n"
"QHeaderView::section:vertical{\n"
"background-color: transparent;\n"
"color:black; \n"
"font-size:12px;\n"
"border-radius:0px;\n"
"border-right:2px solid #BCC6A1;\n"
"margin-right:5px;\n"
"margin-bottom:4px;\n"
"font-style: italic;\n"
"padding-left:8px;\n"
"padding-top:9px;\n"
"padding-bottom:6px;\n"
"margin-top:-4px;\n"
"spacing:10px;\n"
"}\n"
"\n"
"/*АКТИВНЫЕ СЕКЦИИ ПРИ НАВЕДЕНИИ!*/\n"
"\n"
"\n"
"/*ячейка при наведении*/\n"
"QTableWidget::item:hover {\n"
"    background-color:#E1E5C3;\n"
"    border-radius: 3px;\n"
"}\n"
"/* Горизонтальный активный сектор*/\n"
"QHeaderView::section:horizontal:hover{\n"
"background-color: #E1E5C3;\n"
"border-bottom:2px solid #BCC6A1;\n"
"border-radius: 5px;\n"
"\n"
"}\n"
"/* Вертикальный активный сектор*/\n"
"QHeaderView::section:vertical:hover{\n"
"background-color: #E1E5C3;\n"
"border-right:2px solid #BCC6A1;\n"
"border-radius: 5px;\n"
"}\n"
"/*выделенная строка*/\n"
"QTableWidget::item:selected {\n"
"    background-color: #FBFFD8;\n"
"    border-radius: 3px;\n"
"color:black;\n"
"\n"
"}\n"
"/* Левый квадрат*/\n"
"QTableCornerButton::section {\n"
"   background-color: transparent;\n"
"margin-top:12px;\n"
"margin-bottom:18px;\n"
"margin-right:22px;\n"
"margin-left:8px;\n"
"border-image: url(:/icons/icons_images/database.svg) 0 0 0 0 stretch stretch;\n"
"    \n"
"    \n"
"}")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_10.addWidget(self.tableWidget)
        self.frame_30 = QtWidgets.QFrame(self.frame_24)
        self.frame_30.setStyleSheet("background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(20)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        self.frame_31.setStyleSheet("*{\n"
"background-color:transparent;\n"
"border: 3px solid transparent;\n"
"}\n"
"QPushButton {\n"
"border-radius:8px;\n"
"}\n"
"\n"
"")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_12.setEnabled(True)
        self.pushButton_12.setMinimumSize(QtCore.QSize(40, 35))
        self.pushButton_12.setStyleSheet("QPushButton:enabled{\n"
"background-color:rgb(114, 255, 123);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(46, 239, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(122, 255, 101);\n"
"}\n"
"")
        self.pushButton_12.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons_images/plus-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon3)
        self.pushButton_12.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_17.addWidget(self.pushButton_12)
        self.horizontalLayout_16.addWidget(self.frame_31, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.frame_30)
        self.gridLayout_4.addWidget(self.frame_24, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setStyleSheet("background-color:transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setMinimumSize(QtCore.QSize(0, 40))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:transparent;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.frame_51 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_51.sizePolicy().hasHeightForWidth())
        self.frame_51.setSizePolicy(sizePolicy)
        self.frame_51.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("a_FuturaRoundTitulSh")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame_51.setFont(font)
        self.frame_51.setStyleSheet("background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;\n"
"")
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_21.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_52 = QtWidgets.QFrame(self.frame_51)
        self.frame_52.setStyleSheet("background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;")
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_52)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_53 = QtWidgets.QFrame(self.frame_52)
        self.frame_53.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_53.setStyleSheet("QFrame{\n"
"width:50%;\n"
"}\n"
"*{\n"
"background-color:transparent;\n"
"border: 3px solid transparent;\n"
"}\n"
"QPushButton {\n"
"border-radius:8px;\n"
"}\n"
"\n"
"")
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_53)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.radioButton = QtWidgets.QRadioButton(self.frame_53)
        self.radioButton.setEnabled(True)
        self.radioButton.setMinimumSize(QtCore.QSize(35, 33))
        self.radioButton.setMaximumSize(QtCore.QSize(35, 33))
        self.radioButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton.setStyleSheet("\n"
"\n"
"QRadioButton {\n"
"    background-color:       transparent;\n"
"    color:                  rgb(95, 95, 94);\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"width: 27px;\n"
"height: 27px;\n"
"    border-radius:          14px;\n"
"    border:1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       rgb(114, 255, 123);\n"
"\n"
"       image:url(:/icons/icons_images/check.svg) stretch stretch;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(200, 208, 171);\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:unchecked:hover {\n"
"    background-color:      rgb(225, 229, 195);\n"
"    color:                  rgb(95, 95, 94);\n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover {\n"
"    background-color:       rgb(46, 239, 46);\n"
"    color:                  rgb(95, 95, 94);\n"
"\n"
"}\n"
"QRadioButton::indicator:disabled {\n"
"    background-color:       transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_27.addWidget(self.radioButton)
        self.horizontalLayout_26.addWidget(self.frame_53)
        self.frame_54 = QtWidgets.QFrame(self.frame_52)
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_54)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_54)
        self.comboBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 34))
        font = QtGui.QFont()
        font.setFamily("57")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_2.setStyleSheet("/*стиль комбобокса*/\n"
"QComboBox{\n"
"border:1px solid transparent;\n"
"border-radius: 8px;\n"
"padding-left:10px;\n"
"background-color: #E1E5C3;\n"
"spacing:15px;\n"
"}\n"
"/*стиль комбобокса при наводке*/\n"
"QComboBox:hover{\n"
"background-color:#FBFFD8;\n"
"}\n"
"\n"
"/*кнопка стрелки*/\n"
"QComboBox::drop-down{\n"
"border-radius: 0px;\n"
"border:0px;\n"
"}\n"
"/*стиль стрелочки*/\n"
"QComboBox::down-arrow{\n"
"image: url(:/icons/icons_images/arrow-down.svg);\n"
"width:18px;\n"
"height:18px;\n"
"margin-right:16px;\n"
"}\n"
"\n"
"\n"
"\n"
"/*стиль выпадающий список*/\n"
"QListView{\n"
"border-radius: 0px;\n"
"background-color:transparent;\n"
"qproperty-fucusPolicy: \'NoFocus\';\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"border-radius: 8px;\n"
"  selection-background-color: #FBFFD8;\n"
"outline: 0px;\n"
"}\n"
"\n"
"QComboBox:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"\n"
"\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_22.addWidget(self.comboBox_2)
        self.horizontalLayout_26.addWidget(self.frame_54)
        self.verticalLayout_21.addWidget(self.frame_52)
        self.verticalLayout_6.addWidget(self.frame_51)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.centralwidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Заголовок"))
        self.label_4.setText(_translate("Dialog", "продукт не выбран"))
        self.label_7.setText(_translate("Dialog", "Масса"))
        self.label_6.setText(_translate("Dialog", "Стоимость"))
        self.tableWidget.setSortingEnabled(False)
        self.label_10.setText(_translate("Dialog", "Доступные продукты"))
from Custom_Widgets.Widgets import *
from forms.icons import icons_rc