# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_edit_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 486)
        Dialog.setStyleSheet("QDialog{\n"
"border:2px solid gray;\n"
"}\n"
"*{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(191, 198, 155, 255), stop:1 rgba(186, 201, 153, 255));\n"
"}\n"
"QTabWidget::pane {\n"
" border: 0;\n"
" }\n"
"\n"
"QPushButton{\n"
"background-color:white;\n"
"color:black;\n"
"height:30px;\n"
"}\n"
"QTableWidget{\n"
"background-color:#071e26;\n"
"}\n"
"QTextBrowser{\n"
"background-color:#071e26;\n"
"}\n"
"Qlabel{\n"
"}\n"
"QScrollBar:vertical {\n"
"            border: 1px solid rgb(200, 208, 171);\n"
"            border-radius: 5px;\n"
"            background-color:#C8D0AB;\n"
"            width:18px;    \n"
"            margin: 0px px 3px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"            min-height: 0px;\n"
"            border-top: 2px solid black;\n"
"        border-bottom: 2px solid black;\n"
"            border-radius: 4px;\n"
"            background-color: rgb(186, 201, 153);\n"
"            margin-top:-1px;\n"
"        }\n"
"QScrollBar::handle:vertical:hover {         \n"
"           background-color: #E1E5C3;\n"
"        }\n"
"QScrollBar::handle:vertical:pressed {         \n"
"           background-color:#FBFFD8;\n"
"        }\n"
"\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"\n"
"#centralwidget{\n"
"    background-color: black;\n"
"}\n"
"QPushButton{\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"QTableWidget{\n"
"background-color:black;\n"
"}\n"
"\n"
"MainWindow{\n"
"    border-radius: 10px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.centralwidget = QtWidgets.QFrame(Dialog)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"border-top:2px solid gray;\n"
"}")
        self.centralwidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centralwidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 31))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 33))
        self.header_frame.setStyleSheet("background-color: rgb(9, 5, 13);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.header_frame)
        self.frame_11.setMinimumSize(QtCore.QSize(95, 29))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.close_window_button = QtWidgets.QPushButton(self.frame_11)
        self.close_window_button.setMinimumSize(QtCore.QSize(49, 0))
        self.close_window_button.setMaximumSize(QtCore.QSize(16777215, 33))
        self.close_window_button.setStyleSheet("#close_window_button:hover {\n"
"   background: red;\n"
"   border: 2px solid #d0d0d0;\n"
"    border-radius: 4px\n"
"}")
        self.close_window_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons_images/bar_x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_button.setIcon(icon)
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_8.addWidget(self.close_window_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_7.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.header_frame)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(20, 10, 20, 20)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_39 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_39.sizePolicy().hasHeightForWidth())
        self.frame_39.setSizePolicy(sizePolicy)
        self.frame_39.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("a_FuturaRoundTitulSh")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame_39.setFont(font)
        self.frame_39.setStyleSheet("*{\n"
"background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;\n"
"}\n"
"QLineEdit{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"QLineEdit:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"\n"
"\n"
"#label_text_error{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}\n"
"#label_price_error{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}\n"
"#label_8{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_14.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_6 = QtWidgets.QFrame(self.frame_39)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 2, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("font: rgb(175, 175, 175)")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.label_text_error = QtWidgets.QLabel(self.frame_6)
        self.label_text_error.setMinimumSize(QtCore.QSize(0, 15))
        self.label_text_error.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_text_error.setFont(font)
        self.label_text_error.setText("")
        self.label_text_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_text_error.setObjectName("label_text_error")
        self.verticalLayout_2.addWidget(self.label_text_error)
        self.verticalLayout_14.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.frame_39)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.comboBox = QtWidgets.QComboBox(self.frame_7)
        self.comboBox.setEnabled(True)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("/*стиль комбобокса*/\n"
"QComboBox{\n"
"border:1px solid transparent;\n"
"border-radius: 8px;\n"
"padding-left:10px;\n"
"background-color: #E1E5C3;\n"
"spacing:15px;\n"
"}\n"
"/*стиль комбобокса при наводке*/\n"
"QComboBox:hover{\n"
"background-color:#FBFFD8;\n"
"}\n"
"\n"
"/*кнопка стрелки*/\n"
"QComboBox::drop-down{\n"
"border-radius: 0px;\n"
"border:0px;\n"
"}\n"
"/*стиль стрелочки*/\n"
"QComboBox::down-arrow{\n"
"image: url(:/icons/icons_images/arrow-down.svg);\n"
"width:18px;\n"
"height:18px;\n"
"margin-right:16px;\n"
"}\n"
"\n"
"\n"
"\n"
"/*стиль выпадающий список*/\n"
"QListView{\n"
"border-radius: 0px;\n"
"background-color:transparent;\n"
"qproperty-fucusPolicy: \'NoFocus\';\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"border-radius: 8px;\n"
"  selection-background-color: #FBFFD8;\n"
"outline: 0px;\n"
"}\n"
"\n"
"QComboBox:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 15))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayout_14.addWidget(self.frame_3)
        self.frame_8 = QtWidgets.QFrame(self.frame_39)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 2, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.label_price_error = QtWidgets.QLabel(self.frame_8)
        self.label_price_error.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_price_error.sizePolicy().hasHeightForWidth())
        self.label_price_error.setSizePolicy(sizePolicy)
        self.label_price_error.setMinimumSize(QtCore.QSize(0, 15))
        self.label_price_error.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_price_error.setFont(font)
        self.label_price_error.setText("")
        self.label_price_error.setScaledContents(False)
        self.label_price_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_price_error.setWordWrap(False)
        self.label_price_error.setObjectName("label_price_error")
        self.verticalLayout_4.addWidget(self.label_price_error)
        self.verticalLayout_14.addWidget(self.frame_8)
        self.frame_4 = QtWidgets.QFrame(self.frame_39)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("*{\n"
"background-color:transparent;\n"
"border: 3px solid transparent;\n"
"}\n"
"QPushButton {\n"
"border-radius:8px;\n"
"}\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setMinimumSize(QtCore.QSize(40, 35))
        self.pushButton_11.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton:enabled{\n"
"background-color:rgb(114, 255, 123);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(46, 239, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(122, 255, 101);\n"
"}\n"
"")
        self.pushButton_11.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons_images/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 35))
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton:enabled{\n"
"background-color:rgb(255, 73, 73);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(255, 73, 73);\n"
"}\n"
"")
        self.pushButton_10.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons_images/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon2)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.verticalLayout_14.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.frame_39, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout.addWidget(self.centralwidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование"))
        self.label_2.setText(_translate("Dialog", "Название"))
        self.label_7.setText(_translate("Dialog", "Масса"))
        self.label_6.setText(_translate("Dialog", "Стоимость"))
        self.label.setText(_translate("Dialog", "Заголовок"))
from Custom_Widgets.Widgets import *
from forms.icons import icons_rc
