# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_yes_no.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 269)
        Dialog.setStyleSheet("*{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(191, 198, 155, 255), stop:1 rgba(186, 201, 153, 255));\n"
"}\n"
"QTabWidget::pane {\n"
" border: 0;\n"
" }\n"
"\n"
"QPushButton{\n"
"background-color:white;\n"
"color:black;\n"
"height:30px;\n"
"}\n"
"QTableWidget{\n"
"background-color:#071e26;\n"
"}\n"
"QTextBrowser{\n"
"background-color:#071e26;\n"
"}\n"
"Qlabel{\n"
"}\n"
"QScrollBar:vertical {\n"
"            border: 1px solid rgb(200, 208, 171);\n"
"            border-radius: 5px;\n"
"            background-color:#C8D0AB;\n"
"            width:18px;    \n"
"            margin: 0px px 3px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"            min-height: 0px;\n"
"            border-top: 2px solid black;\n"
"        border-bottom: 2px solid black;\n"
"            border-radius: 4px;\n"
"            background-color: rgb(186, 201, 153);\n"
"            margin-top:-1px;\n"
"        }\n"
"QScrollBar::handle:vertical:hover {         \n"
"           background-color: #E1E5C3;\n"
"        }\n"
"QScrollBar::handle:vertical:pressed {         \n"
"           background-color:#FBFFD8;\n"
"        }\n"
"\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"\n"
"#centralwidget{\n"
"    background-color: black;\n"
"}\n"
"QPushButton{\n"
"background-color: white;\n"
"border-radius: 20px;\n"
"}\n"
"QTableWidget{\n"
"background-color:black;\n"
"}\n"
"\n"
"MainWindow{\n"
"    border-radius: 10px;\n"
"}\n"
"#centralwidget{\n"
"border-top:2px solid gray;\n"
"}")
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.centralwidget = QtWidgets.QFrame(Dialog)
        self.centralwidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centralwidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 31))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 29))
        self.header_frame.setStyleSheet("background-color: rgb(9, 5, 13);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.header_frame)
        self.frame_11.setMinimumSize(QtCore.QSize(95, 0))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 2)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.close_window_button = QtWidgets.QPushButton(self.frame_11)
        self.close_window_button.setMinimumSize(QtCore.QSize(49, 0))
        self.close_window_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.close_window_button.setStyleSheet("#close_window_button:hover {\n"
"   background: red;\n"
"   border: 2px solid #d0d0d0;\n"
"    border-radius: 4px\n"
"}")
        self.close_window_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons_images/bar_x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_button.setIcon(icon)
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_8.addWidget(self.close_window_button, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_7.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight)
        self.gridLayout_2.addWidget(self.header_frame, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(20, 10, 20, 20)
        self.gridLayout_4.setHorizontalSpacing(20)
        self.gridLayout_4.setVerticalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("*{\n"
"background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;\n"
"}\n"
"QLineEdit{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"QTextBrowser{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"\n"
"#label_price_error{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}\n"
"\n"
"#label_text_error{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(20, 20, 20, 10)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_39 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_39.sizePolicy().hasHeightForWidth())
        self.frame_39.setSizePolicy(sizePolicy)
        self.frame_39.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("a_FuturaRoundTitulSh")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame_39.setFont(font)
        self.frame_39.setStyleSheet("*{\n"
"background-color:#C8D0AB;\n"
"border: 3px solid transparent;\n"
"border-radius:30px;\n"
"}\n"
"QLineEdit{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"QTextBrowser{\n"
"background-color:rgb(186, 201, 153);\n"
"min-height:28px;\n"
"border-radius:8px;\n"
"selection-color: black; \n"
"selection-background-color: rgb(225, 229, 195);\n"
"}\n"
"\n"
"#label_price_error{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}\n"
"\n"
"#label_text_error{\n"
"border: 0px solid transparent;\n"
"border-radius:0px;\n"
"color:red;\n"
"min-height:15px;\n"
"max-height:20px;\n"
"margin-left:5px;\n"
"}")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.frame_39)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_39)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("*{\n"
"background-color:transparent;\n"
"border: 3px solid transparent;\n"
"}\n"
"QPushButton {\n"
"border-radius:8px;\n"
"}\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setMinimumSize(QtCore.QSize(40, 35))
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton:enabled{\n"
"background-color:rgb(114, 255, 123);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(46, 239, 46);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(122, 255, 101);\n"
"}\n"
"")
        self.pushButton_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons_images/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setMinimumSize(QtCore.QSize(40, 35))
        self.pushButton_9.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton:enabled{\n"
"background-color:rgb(255, 73, 73);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color:rgb(188, 198, 161);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(255, 73, 73);\n"
"}\n"
"")
        self.pushButton_9.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons_images/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.verticalLayout_14.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frame_39, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.centralwidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Текст"))
        self.label.setText(_translate("Dialog", "Заголовок"))
from Custom_Widgets.Widgets import *
from forms.icons import icons_rc

